# Generated by Django 2.1.2 on 2018-10-08 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('size1', models.CharField(max_length=200)),
                ('size2', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=20)),
                ('price2', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('imageUrl', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
