# Generated by Django 2.1.2 on 2018-10-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
